# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bravitzlana', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
